owner: keywordnew
repo: scaling-robot
user-agent: keywordnew

sites:
  - name: BC Hydro
    url: https://www.google.com
    method: GET
    logoUrl: https://nilspace.xyz/content/images/2023/05/power.svg

status-website:
  baseUrl: /scaling-robot
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 'Vancouver BC 🇨🇦'
  introTitle: core services status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
