owner: keywordnew
repo: scaling-robot
user-agent: keywordnew

sites:
  - name: BC Hydro
    url: https://www.bchydro.com/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/power-1.png
  - name: Translink
    url: https://www.translink.ca/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/transportation-1.png
  

status-website:
  baseUrl: /scaling-robot
  name: 'Neighbourhood Cyber'
  logoUrl: https://nilspace.xyz/content/images/2023/05/favicon.png
  favicon: https://nilspace.xyz/content/images/2023/05/favicon.png
  introTitle: 'Vancouver BC 🇨🇦'
  introMessage: 'check if critical infrastructure may be down, or use [GitHub ↗️](https://github.com/keywordnew/scaling-robot) to "Watch" and get notified'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Neighbourhoods
      href: https://github.com/$OWNER?tab=repositories&q=watchtower
