owner: keywordnew
repo: scaling-robot
user-agent: keywordnew

sites:
  - name: BC Hydro
    url: https://www.bchydro.com/
    method: GET
    logoUrl: https://nilspace.xyz/content/images/2023/05/power.png

status-website:
  baseUrl: /scaling-robot
  name: 'Neighbourhood Cyber 🔮'
  introTitle: 'Vancouver BC 🇨🇦'
  introMessage: 'check if core infrastructure may be down, or use [GitHub ↗️](https://github.com/HelSec/uptime) to "Watch" and get notified'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
